/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author dcuvelie
 */
public class Lobby extends javax.swing.JPanel {

    /**
     * Creates new form Ingelogd
     */
    public Lobby() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonNaarReviews = new javax.swing.JButton();
        jButtonNaarOrder = new javax.swing.JButton();
        jButtonNaarAccount = new javax.swing.JButton();

        jLabel1.setText("Welkom : ");

        jLabel2.setText("hier moet naam komen automatisch");

        jButtonNaarReviews.setText("Reviews Maken");

        jButtonNaarOrder.setText("Order Samenstellen");

        jButtonNaarAccount.setText("Account wijzigen ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNaarAccount)
                    .addComponent(jButtonNaarOrder)
                    .addComponent(jButtonNaarReviews)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addComponent(jButtonNaarReviews)
                .addGap(29, 29, 29)
                .addComponent(jButtonNaarOrder)
                .addGap(33, 33, 33)
                .addComponent(jButtonNaarAccount)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNaarAccount;
    private javax.swing.JButton jButtonNaarOrder;
    private javax.swing.JButton jButtonNaarReviews;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
